# build stage
FROM golang as builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build

RUN go install github.com/cosmtrek/air@latest

COPY ./ /app/

ENTRYPOINT ["air", "-c", ".air.toml"]
